// GENERATED by scripts/generate-registry.sh
import { Registry } from "@cosmjs/proto-signing";
import { MsgCreateToken, MsgCreateTokenResponse } from "./coin/tx";
import { MsgAddCollateral, MsgAddCollateralResponse, MsgRemoveCollateral, MsgRemoveCollateralResponse, MsgAddDebt, MsgAddDebtResponse, MsgRemoveDebt, MsgRemoveDebtResponse, MsgCreateVaultType, MsgCreateVaultTypeResponse } from "./collateralizeddebtposition/tx";
import { MsgSetFee, MsgSetFeeResponse } from "./fee/tx";
import { MsgCreatePool, MsgCreatePoolResponse } from "./liquiditypool/tx";
import { MsgCreateMarket, MsgCreateMarketResponse, MsgUpdateMarket, MsgUpdateMarketResponse } from "./market/tx";
import { MsgCreateOracle, MsgCreateOracleResponse, MsgCreateVote, MsgCreateVoteResponse } from "./oracle/tx";
import { MsgSetTradingFlag, MsgSetTradingFlagResponse, MsgCreateOrder, MsgCreateOrderResponse, MsgEditOrder, MsgEditOrderResponse, MsgCancelOrder, MsgCancelOrderResponse, MsgCancelAll, MsgCancelAllResponse } from "./order/tx";
import { MsgUpdateProfile, MsgUpdateProfileResponse } from "./profile/tx";
import { MsgCreateSubAccount, MsgCreateSubAccountResponse, MsgActivateSubAccount, MsgActivateSubAccountResponse, MsgRemoveSubAccount, MsgRemoveSubAccountResponse } from "./subaccount/tx";

export const registry = new Registry();

registry.register("/Switcheo.tradehubcosmos.coin.MsgCreateToken", MsgCreateToken);
registry.register("/Switcheo.tradehubcosmos.coin.MsgCreateTokenResponse", MsgCreateTokenResponse);

registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgAddCollateral", MsgAddCollateral);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgAddCollateralResponse", MsgAddCollateralResponse);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgRemoveCollateral", MsgRemoveCollateral);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgRemoveCollateralResponse", MsgRemoveCollateralResponse);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgAddDebt", MsgAddDebt);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgAddDebtResponse", MsgAddDebtResponse);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgRemoveDebt", MsgRemoveDebt);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgRemoveDebtResponse", MsgRemoveDebtResponse);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgCreateVaultType", MsgCreateVaultType);
registry.register("/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgCreateVaultTypeResponse", MsgCreateVaultTypeResponse);

registry.register("/Switcheo.tradehubcosmos.fee.MsgSetFee", MsgSetFee);
registry.register("/Switcheo.tradehubcosmos.fee.MsgSetFeeResponse", MsgSetFeeResponse);

registry.register("/Switcheo.tradehubcosmos.liquiditypool.MsgCreatePool", MsgCreatePool);
registry.register("/Switcheo.tradehubcosmos.liquiditypool.MsgCreatePoolResponse", MsgCreatePoolResponse);

registry.register("/Switcheo.tradehubcosmos.market.MsgCreateMarket", MsgCreateMarket);
registry.register("/Switcheo.tradehubcosmos.market.MsgCreateMarketResponse", MsgCreateMarketResponse);
registry.register("/Switcheo.tradehubcosmos.market.MsgUpdateMarket", MsgUpdateMarket);
registry.register("/Switcheo.tradehubcosmos.market.MsgUpdateMarketResponse", MsgUpdateMarketResponse);

registry.register("/Switcheo.tradehubcosmos.oracle.MsgCreateOracle", MsgCreateOracle);
registry.register("/Switcheo.tradehubcosmos.oracle.MsgCreateOracleResponse", MsgCreateOracleResponse);
registry.register("/Switcheo.tradehubcosmos.oracle.MsgCreateVote", MsgCreateVote);
registry.register("/Switcheo.tradehubcosmos.oracle.MsgCreateVoteResponse", MsgCreateVoteResponse);

registry.register("/Switcheo.tradehubcosmos.order.MsgSetTradingFlag", MsgSetTradingFlag);
registry.register("/Switcheo.tradehubcosmos.order.MsgSetTradingFlagResponse", MsgSetTradingFlagResponse);
registry.register("/Switcheo.tradehubcosmos.order.MsgCreateOrder", MsgCreateOrder);
registry.register("/Switcheo.tradehubcosmos.order.MsgCreateOrderResponse", MsgCreateOrderResponse);
registry.register("/Switcheo.tradehubcosmos.order.MsgEditOrder", MsgEditOrder);
registry.register("/Switcheo.tradehubcosmos.order.MsgEditOrderResponse", MsgEditOrderResponse);
registry.register("/Switcheo.tradehubcosmos.order.MsgCancelOrder", MsgCancelOrder);
registry.register("/Switcheo.tradehubcosmos.order.MsgCancelOrderResponse", MsgCancelOrderResponse);
registry.register("/Switcheo.tradehubcosmos.order.MsgCancelAll", MsgCancelAll);
registry.register("/Switcheo.tradehubcosmos.order.MsgCancelAllResponse", MsgCancelAllResponse);

registry.register("/Switcheo.tradehubcosmos.profile.MsgUpdateProfile", MsgUpdateProfile);
registry.register("/Switcheo.tradehubcosmos.profile.MsgUpdateProfileResponse", MsgUpdateProfileResponse);

registry.register("/Switcheo.tradehubcosmos.subaccount.MsgCreateSubAccount", MsgCreateSubAccount);
registry.register("/Switcheo.tradehubcosmos.subaccount.MsgCreateSubAccountResponse", MsgCreateSubAccountResponse);
registry.register("/Switcheo.tradehubcosmos.subaccount.MsgActivateSubAccount", MsgActivateSubAccount);
registry.register("/Switcheo.tradehubcosmos.subaccount.MsgActivateSubAccountResponse", MsgActivateSubAccountResponse);
registry.register("/Switcheo.tradehubcosmos.subaccount.MsgRemoveSubAccount", MsgRemoveSubAccount);
registry.register("/Switcheo.tradehubcosmos.subaccount.MsgRemoveSubAccountResponse", MsgRemoveSubAccountResponse);

export const TxTypes = {
  "MsgCreateToken": "/Switcheo.tradehubcosmos.coin.MsgCreateToken",
  "MsgCreateTokenResponse": "/Switcheo.tradehubcosmos.coin.MsgCreateTokenResponse",
  "MsgAddCollateral": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgAddCollateral",
  "MsgAddCollateralResponse": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgAddCollateralResponse",
  "MsgRemoveCollateral": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgRemoveCollateral",
  "MsgRemoveCollateralResponse": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgRemoveCollateralResponse",
  "MsgAddDebt": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgAddDebt",
  "MsgAddDebtResponse": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgAddDebtResponse",
  "MsgRemoveDebt": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgRemoveDebt",
  "MsgRemoveDebtResponse": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgRemoveDebtResponse",
  "MsgCreateVaultType": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgCreateVaultType",
  "MsgCreateVaultTypeResponse": "/Switcheo.tradehubcosmos.collateralizeddebtposition.MsgCreateVaultTypeResponse",
  "MsgSetFee": "/Switcheo.tradehubcosmos.fee.MsgSetFee",
  "MsgSetFeeResponse": "/Switcheo.tradehubcosmos.fee.MsgSetFeeResponse",
  "MsgCreatePool": "/Switcheo.tradehubcosmos.liquiditypool.MsgCreatePool",
  "MsgCreatePoolResponse": "/Switcheo.tradehubcosmos.liquiditypool.MsgCreatePoolResponse",
  "MsgCreateMarket": "/Switcheo.tradehubcosmos.market.MsgCreateMarket",
  "MsgCreateMarketResponse": "/Switcheo.tradehubcosmos.market.MsgCreateMarketResponse",
  "MsgUpdateMarket": "/Switcheo.tradehubcosmos.market.MsgUpdateMarket",
  "MsgUpdateMarketResponse": "/Switcheo.tradehubcosmos.market.MsgUpdateMarketResponse",
  "MsgCreateOracle": "/Switcheo.tradehubcosmos.oracle.MsgCreateOracle",
  "MsgCreateOracleResponse": "/Switcheo.tradehubcosmos.oracle.MsgCreateOracleResponse",
  "MsgCreateVote": "/Switcheo.tradehubcosmos.oracle.MsgCreateVote",
  "MsgCreateVoteResponse": "/Switcheo.tradehubcosmos.oracle.MsgCreateVoteResponse",
  "MsgSetTradingFlag": "/Switcheo.tradehubcosmos.order.MsgSetTradingFlag",
  "MsgSetTradingFlagResponse": "/Switcheo.tradehubcosmos.order.MsgSetTradingFlagResponse",
  "MsgCreateOrder": "/Switcheo.tradehubcosmos.order.MsgCreateOrder",
  "MsgCreateOrderResponse": "/Switcheo.tradehubcosmos.order.MsgCreateOrderResponse",
  "MsgEditOrder": "/Switcheo.tradehubcosmos.order.MsgEditOrder",
  "MsgEditOrderResponse": "/Switcheo.tradehubcosmos.order.MsgEditOrderResponse",
  "MsgCancelOrder": "/Switcheo.tradehubcosmos.order.MsgCancelOrder",
  "MsgCancelOrderResponse": "/Switcheo.tradehubcosmos.order.MsgCancelOrderResponse",
  "MsgCancelAll": "/Switcheo.tradehubcosmos.order.MsgCancelAll",
  "MsgCancelAllResponse": "/Switcheo.tradehubcosmos.order.MsgCancelAllResponse",
  "MsgUpdateProfile": "/Switcheo.tradehubcosmos.profile.MsgUpdateProfile",
  "MsgUpdateProfileResponse": "/Switcheo.tradehubcosmos.profile.MsgUpdateProfileResponse",
  "MsgCreateSubAccount": "/Switcheo.tradehubcosmos.subaccount.MsgCreateSubAccount",
  "MsgCreateSubAccountResponse": "/Switcheo.tradehubcosmos.subaccount.MsgCreateSubAccountResponse",
  "MsgActivateSubAccount": "/Switcheo.tradehubcosmos.subaccount.MsgActivateSubAccount",
  "MsgActivateSubAccountResponse": "/Switcheo.tradehubcosmos.subaccount.MsgActivateSubAccountResponse",
  "MsgRemoveSubAccount": "/Switcheo.tradehubcosmos.subaccount.MsgRemoveSubAccount",
  "MsgRemoveSubAccountResponse": "/Switcheo.tradehubcosmos.subaccount.MsgRemoveSubAccountResponse"
}

