// https://github.com/WalletConnect/EIP6963/blob/master/src/utils/constants.ts
export enum SupportedEip6963Provider {
  Brave = "Brave",
  Enkrypt = "Enkrypt",
  Zerion = "Zerion",
  TokenPocket = "TokenPocket",
  Iron = "Iron",
  Rainbow = "Rainbow",
  Phantom = "Phantom",
  OKX = "OKX",
  Spot = "Spot",
  XDEFI = "XDEFI",
  Talisman = "Talisman",
  Frontier = "Frontier",
  SafePal = "SafePal",
  Sequence = "Sequence",
  RabbyWallet = "Rabby Wallet",
  TrustWallet = "Trust Wallet",
  Coinbase = "Coinbase",
  MetaMask = "MetaMask",
  CryptoWallet = "Crypto.com Wallet",
  RoninWallet = "Ronin Wallet",
  MetaMaskInstitutional = "MetaMask Institutional",
  BitgetWallet = "Bitget Wallet",
  Fluvi = "Fluvi",
  SafeheronWallet = "Safeheron Wallet",
}
