export const whitelistCosmosExports: { [name: string]: string } = {
  'App': 'cosmos/app/v1alpha1',
  'Auth': 'cosmos/auth/v1beta1',
  'Authz': 'cosmos/authz/v1beta1',
  'Bank': 'cosmos/bank/v1beta1',
  'Capability': 'cosmos/capability/v1beta1',
  'Crisis': 'cosmos/crisis/v1beta1',
  'Distribution': 'cosmos/distribution/v1beta1',
  'Evidence': 'cosmos/evidence/v1beta1',
  'Feegrant': 'cosmos/feegrant/v1beta1',
  'GenUtil': 'cosmos/genutil/v1beta1',
  'GovV1': 'cosmos/gov/v1',
  'GovV1beta1': 'cosmos/gov/v1beta1',
  'Group': 'cosmos/group/v1',
  'Mint': 'cosmos/mint/v1beta1',
  'Msg': 'cosmos/msg/v1',
  'Nft': 'cosmos/nft/v1beta1',
  'OrmV1': 'cosmos/orm/v1',
  'OrmV1alpha1': 'cosmos/orm/v1alpha1',
  'Params': 'cosmos/params/v1beta1',
  'Slashing': 'cosmos/slashing/v1beta1',
  'Staking': 'cosmos/staking/v1beta1',
  'Tx': 'cosmos/tx/v1beta1',
  'Upgrade': 'cosmos/upgrade/v1beta1',
  'Vesting': 'cosmos/vesting/v1beta1',
};

export const whitelistIbcExports: { [name: string]: string[] } = {
  'Controller': ['ibc/applications/interchain_accounts/controller/v1'],
  'Fee': ['ibc/applications/fee/v1'],
  'Host': ['ibc/applications/interchain_accounts/host/v1'],
  'InterchainTypes': ['ibc/applications/interchain_accounts/v1'],
  'TranferV1': ['ibc/applications/transfer/v1'],
  'TransferV2': ['ibc/applications/transfer/v2'],
  'Channel': ['ibc/core/channel/v1'],
  'Client': ['ibc/core/client/v1'],
  'Commitment': ['ibc/core/commitment/v1'],
  'Connection': ['ibc/core/connection/v1'],
  'LocalHost': ['ibc/lightclients/localhost/v1'],
  'Solomachine': ['ibc/lightclients/solomachine/v1'],
  'Tendermint': ['ibc/lightclients/tendermint/v1'],
};
