#!/usr/bin/env bash

set -eo pipefail

echo "Generating registry…"

TX_FILES=$(find src/codec -path -prune -o -name '*.ts')
echo $TX_FILES
REGISTRY_FILE=src/codec/index.ts
COSMOS_MODELS_FILE=src/codec/cosmos-models.ts
IBC_MODELS_FILE=src/codec/ibc-models.ts
POLYNETWORK_MODELS_FILE=src/codec/polynetwork-models.ts

ts-node ./scripts/generate-cosmos-models.ts $PWD $COSMOS_MODELS_FILE
ts-node ./scripts/generate-ibc-models.ts $PWD $IBC_MODELS_FILE
ts-node ./scripts/generate-polynetwork-models.ts $PWD $POLYNETWORK_MODELS_FILE
echo "// GENERATED by scripts/generate-registry.sh" > $REGISTRY_FILE
ts-node ./scripts/generate-registry.ts $TX_FILES $PWD $REGISTRY_FILE $POLYNETWORK_MODELS_FILE $COSMOS_MODELS_FILE $IBC_MODELS_FILE >> $REGISTRY_FILE
