#!/usr/bin/env bash

set -eo pipefail

echo "Generating registry…"

TX_FILES=$(find src/codec -path -prune -o -name '*.ts')
echo $TX_FILES
REGISTRY_FILE=src/codec/index.ts
COSMOS_MODELS_FILE=src/codec/cosmos-models.ts

ts-node ./scripts/generate-cosmos-models.ts $PWD $COSMOS_MODELS_FILE
echo "// GENERATED by scripts/generate-registry.sh" > $REGISTRY_FILE
ts-node ./scripts/generate-registry.ts $TX_FILES $PWD $REGISTRY_FILE $COSMOS_MODELS_FILE >> $REGISTRY_FILE
