#!/usr/bin/env node
/* global __dirname, require */
const fs = require("node:fs");
const path = require("node:path");

const abiDirectory = path.resolve(__dirname, "../src/eth/abis");
const names = ["axelarBridge", "balanceReader", "bridgeEntrance", "erc20", "keyStorage", "lockProxy", "nativeDepositer", "vault"];
const contents = ["// GENERATED by scripts/generate-abis.cjs; DO NOT EDIT."];
for (const name of names) {
  const value = JSON.parse(fs.readFileSync(path.join(abiDirectory, `${name}.json`), "utf8"));
  contents.push(`export const ${name} = ${JSON.stringify(value, null, 2)};`);
}
fs.writeFileSync(path.join(abiDirectory, "generated.ts"), `${contents.join("\n\n")}\n`);
