#!/usr/bin/env bash

set -eo pipefail

echo "Generating registry…"

TX_FILES=$(find src/codec -name '*.ts' \
  ! -name 'index.ts' \
  ! -name 'export.ts' \
  ! -name '*-models.ts' \
  ! -name 'model-namespaces.ts' \
  ! -name 'message-metadata.ts' \
  ! -name 'create-registry.ts' \
  ! -name 'registry.ts' | LC_ALL=C sort)
echo $TX_FILES
REGISTRY_FILE=src/codec/index.ts
COSMOS_MODELS_FILE=src/codec/cosmos-models.ts
IBC_MODELS_FILE=src/codec/ibc-models.ts
POLYNETWORK_MODELS_FILE=src/codec/polynetwork-models.ts
ETHERMINT_MODELS_FILE=src/codec/ethermint-models.ts
CARBON_MODELS_FILE=src/codec/carbon-models.ts

ts-node --transpile-only ./scripts/generate-cosmos-models.ts $PWD $COSMOS_MODELS_FILE
ts-node --transpile-only ./scripts/generate-ibc-models.ts $PWD $IBC_MODELS_FILE
ts-node --transpile-only ./scripts/generate-polynetwork-models.ts $PWD $POLYNETWORK_MODELS_FILE
ts-node --transpile-only ./scripts/generate-ethermint-models.ts $PWD $ETHERMINT_MODELS_FILE
ts-node --transpile-only ./scripts/generate-carbon-models.ts $PWD $CARBON_MODELS_FILE
GENERATED_REGISTRY=$(mktemp)
trap 'rm -f "$GENERATED_REGISTRY"' EXIT
echo "// GENERATED by scripts/generate-registry.sh" > "$GENERATED_REGISTRY"
ts-node ./scripts/generate-registry.ts $TX_FILES $PWD $REGISTRY_FILE $POLYNETWORK_MODELS_FILE $CARBON_MODELS_FILE $COSMOS_MODELS_FILE $IBC_MODELS_FILE $ETHERMINT_MODELS_FILE >> "$GENERATED_REGISTRY"
node ./scripts/split-generated-registry.cjs "$GENERATED_REGISTRY" src/codec


rm -rf ./scripts/protobuf-def.json